In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [2]:
connection_url = URL.create(
    "mysql+mysqlconnector",
    username="root",
    password="@sql&form$PHP05",
    host="localhost",
    database="vehicle_sales"
)

In [3]:
engine = create_engine(connection_url)

In [4]:
tables = ['customers', 'inventory_details', 'vehicle_info', 'vehicle_sold']
dfs = {}

for table in tables:
    query = f"SELECT * FROM {table}"
    # Pass the SQLAlchemy 'engine' here instead of the raw connection
    dfs[table] = pd.read_sql(query, con=engine)

In [5]:
# Loop through the dictionary and display the first 5 rows of each table
for table_name, df in dfs.items():
    print(f"--- Table: {table_name} ---")
    display(df.head())  # Using display() makes it look like a clean table in Jupyter
    print("\n") # Adds a bit of space between tables

--- Table: customers ---

  sale_id   customer_name                 contact_info
0  S10001   Charles Smith   charles.smith136@gmail.com
1  S10002   Robert Miller   robert.miller944@gmail.com
2  S10003  Anthony Garcia  anthony.garcia502@gmail.com
3  S10004   Matthew Davis   matthew.davis496@gmail.com
4  S10005    Robert Smith    robert.smith942@gmail.com

--- Table: inventory_details ---

  sale_id region  mileage
0   S1001  North    12000
1   S1002  South      500
2   S1003   West    32000
3   S1004   West       10
4   S1005   West    45000

--- Table: vehicle_info ---

  vehicle_id     make    model  year  body_type fuel_type   msrp
0      V0001  Unknown  Corolla  2022      Sedan  Gasoline  24000
1      V0002     Ford    F-150  2023      Truck    Diesel  45000
2      V0003    Honda    Civic  2021  Hatchback  Gasoline  22000
3      V0004  Unknown  Model 3  2024      Sedan  Electric  42000
4      V0005  Unknown       X5  2022        SUV    Diesel  62000

--- Table: vehicle_sold ---

  sale_id vehicle_id  sale_price  days_on_lot
0   S1001      V0001       23200           15
1   S1002      V0002       43500            5
2   S1003      V0003       21000           45
3   S1004      V0004       58000            2
4   S1005      V0005       58000          120

## Remove Duplicates

### 1. Access the customers DataFrame from your dictionary

In [6]:
customer_df = dfs['customers']
customer_df.head()

  sale_id   customer_name                 contact_info
0  S10001   Charles Smith   charles.smith136@gmail.com
1  S10002   Robert Miller   robert.miller944@gmail.com
2  S10003  Anthony Garcia  anthony.garcia502@gmail.com
3  S10004   Matthew Davis   matthew.davis496@gmail.com
4  S10005    Robert Smith    robert.smith942@gmail.com

In [7]:
customer_df.shape

(1864, 3)

In [8]:
pd.set_option('display.max.rows', None)
customer_df

     sale_id          customer_name                        contact_info
0     S10001          Charles Smith          charles.smith136@gmail.com
1     S10002          Robert Miller          robert.miller944@gmail.com
2     S10003         Anthony Garcia         anthony.garcia502@gmail.com
3     S10004          Matthew Davis          matthew.davis496@gmail.com
4     S10005           Robert Smith           robert.smith942@gmail.com
5     S10006          Mark Gonzalez           mark.gonzalez68@gmail.com
6     S10007          Joseph Garcia          joseph.garcia956@gmail.com
7     S10008         David Gonzalez         david.gonzalez847@gmail.com
8     S10009        Elizabeth Jones        elizabeth.jones706@gmail.com
9      S1001       Thomas Hernandez       thomas.hernandez381@gmail.com
10    S10010         William Thomas         william.thomas983@gmail.com
11    S10011          Mark Martinez          mark.martinez170@gmail.com
12    S10012      Anthony Rodriguez      anthony.rodriguez672@gmail.com
13    S10013      Jennifer Anderson      jennifer.anderson261@gmail.com
14    S10014        William Jackson        william.jackson622@gmail.com
15    S10015       Elizabeth Taylor       elizabeth.taylor953@gmail.com
16    S10016          Richard Jones          richard.jones665@gmail.com
17    S10017           Susan Thomas           susan.thomas381@gmail.com
18    S10018        Sandra Gonzalez        sandra.gonzalez175@gmail.com
19    S10019     Christopher Miller     christopher.miller410@gmail.com
20     S1002      Jennifer Gonzalez      jennifer.gonzalez492@gmail.com
21    S10020        Charles Jackson        charles.jackson728@gmail.com
22    S10021         Thomas Johnson         thomas.johnson345@gmail.com
23    S10022         Betty Anderson         betty.anderson320@gmail.com
24    S10023         Matthew Taylor         matthew.taylor390@gmail.com
25    S10024          Linda Jackson          linda.jackson836@gmail.com
26    S10025            David Davis            david.davis104@gmail.com
27    S10026             John Jones             john.jones247@gmail.com
28    S10027          Charles Davis          charles.davis459@gmail.com
29    S10028            Lisa Martin            lisa.martin677@gmail.com
30    S10029       Patricia Johnson       patricia.johnson921@gmail.com
31     S1003           Nancy Martin           nancy.martin677@gmail.com
32    S10030          Betty Jackson          betty.jackson275@gmail.com
33    S10031          Robert Martin          robert.martin498@gmail.com
34    S10032         Linda Martinez         linda.martinez211@gmail.com
35    S10033      William Rodriguez      william.rodriguez803@gmail.com
36    S10034          Lisa Martinez          lisa.martinez462@gmail.com
37    S10035       Joseph Hernandez       joseph.hernandez257@gmail.com
38    S10036       Matthew Martinez       matthew.martinez479@gmail.com
39    S10037         Jennifer Lopez          jennifer.lopez43@gmail.com
40    S10038          Joseph Miller          joseph.miller342@gmail.com
41    S10039         Richard Martin         richard.martin686@gmail.com
42     S1004      Christopher Davis      christopher.davis479@gmail.com
43    S10040       Anthony Anderson        anthony.anderson95@gmail.com
44    S10041      Christopher Davis      christopher.davis928@gmail.com
45    S10042      Matthew Hernandez      matthew.hernandez146@gmail.com
46    S10043          William Smith           william.smith96@gmail.com
47    S10044         Linda Williams         linda.williams135@gmail.com
48    S10045            Karen Jones             karen.jones68@gmail.com
49    S10046       Barbara Martinez       barbara.martinez439@gmail.com
50    S10047      Patricia Anderson      patricia.anderson247@gmail.com
51    S10048         Mark Hernandez          mark.hernandez69@gmail.com
52    S10049          Mark Williams          mark.williams727@gmail.com
53     S1005           David Wilson           david.wilson488@gmail.com
54    S10050         Anthony Taylor          anthony.taylor44@gmail.com
55    S10051           Thomas Lopez           thomas.lopez273@gmail.com
56    S10052           Sarah Garcia           sarah.garcia292@gmail.com
57    S10053            Linda Brown            linda.brown646@gmail.com
58    S10054          Michael Moore          michael.moore146@gmail.com
59    S10055         David Anderson         david.anderson786@gmail.com
60    S10056        Daniel Anderson        daniel.anderson800@gmail.com
61    S10057      Richard Hernandez       richard.hernandez11@gmail.com
62    S10058         Mark Hernandez         mark.hernandez830@gmail.com
63    S10059             John Jones             john.jones519@gmail.com
64     S1006         Joseph Jackson         joseph.jackson410@gmail.com
65    S10060          Lisa Anderson          lisa.anderson502@gmail.com
66    S10061        Susan Hernandez        susan.hernandez746@gmail.com
67    S10062    Christopher Johnson    christopher.johnson992@gmail.com
68    S10063       Michael Williams       michael.williams175@gmail.com
69    S10064            Linda Smith            linda.smith656@gmail.com
70    S10065          Daniel Martin          daniel.martin827@gmail.com
71    S10066             Mary Davis             mary.davis319@gmail.com
72    S10067            Susan Davis             susan.davis72@gmail.com
73    S10068        Joseph Martinez        joseph.martinez483@gmail.com
74    S10069        Jennifer Thomas        jennifer.thomas678@gmail.com
75     S1007      Patricia Williams      patricia.williams766@gmail.com
76    S10070       Anthony Martinez       anthony.martinez753@gmail.com
77    S10071         Linda Gonzalez         linda.gonzalez368@gmail.com
78    S10072     Margaret Rodriguez     margaret.rodriguez442@gmail.com
79    S10073           Sarah Martin           sarah.martin607@gmail.com
80    S10074         Patricia Davis         patricia.davis779@gmail.com
81    S10075          Jessica Lopez          jessica.lopez624@gmail.com
82    S10076             Lisa Smith             lisa.smith788@gmail.com
83    S10077            Mary Martin            mary.martin162@gmail.com
84    S10078          Barbara Smith          barbara.smith714@gmail.com
85    S10079        Daniel Anderson        daniel.anderson985@gmail.com
86     S1008        Susan Rodriguez        susan.rodriguez909@gmail.com
87    S10080            Betty Davis            betty.davis919@gmail.com
88    S10081           Linda Taylor           linda.taylor479@gmail.com
89    S10082          Joseph Thomas          joseph.thomas426@gmail.com
90    S10083          Mark Anderson          mark.anderson253@gmail.com
91    S10084      William Rodriguez      william.rodriguez450@gmail.com
92    S10085            Susan Jones            susan.jones191@gmail.com
93    S10086      Christopher Lopez      christopher.lopez983@gmail.com
94    S10087         Jessica Taylor         jessica.taylor161@gmail.com
95    S10088           Daniel Lopez           daniel.lopez580@gmail.com
96    S10089         Michael Martin         michael.martin393@gmail.com
97     S1009          Sarah Jackson          sarah.jackson211@gmail.com
98    S10090      Matthew Hernandez      matthew.hernandez782@gmail.com
99    S10091         Karen Gonzalez          karen.gonzalez20@gmail.com
100   S10092          William Lopez          william.lopez572@gmail.com
101   S10093            Nancy Jones            nancy.jones400@gmail.com
102   S10094          Joseph Taylor          joseph.taylor809@gmail.com
103   S10095           Robert Smith           robert.smith839@gmail.com
104   S10096      Margaret Anderson      margaret.anderson455@gmail.com
105   S10097         Nancy Martinez         nancy.martinez396@gmail.com
106   S10098         Jessica Miller         jessica.miller741@gmail.com
107   S10099       William Williams       william.williams815@gmail.com
108    S1010         Patricia Jones         patricia.jones102@gmail.com
109   S10100         William Wilson         william.wilson949@gmail.com
110   S10101           John Johnson           john.johnson723@gmail.com
111   S10102         Mark Rodriguez         mark.rodriguez239@gmail.com
112   S10103           Joseph Davis           joseph.davis168@gmail.com
113   S10104          Richard Brown           richard.brown58@gmail.com
114   S10105        Barbara Johnson        barbara.johnson554@gmail.com
115   S10106          Joseph Miller          joseph.miller571@gmail.com
116   S10107       Sandra Hernandez       sandra.hernandez873@gmail.com
117   S10108            Susan Jones            susan.jones288@gmail.com
118   S10109         Joseph Johnson         joseph.johnson954@gmail.com
119    S1011             Lisa Davis             lisa.davis269@gmail.com
120   S10110           Thomas Davis           thomas.davis246@gmail.com
121   S10111     Christopher Garcia     christopher.garcia127@gmail.com
122   S10112          Anthony Brown           anthony.brown20@gmail.com
123   S10113          Susan Jackson          susan.jackson419@gmail.com
124   S10114          Charles Jones          charles.jones872@gmail.com
125   S10115         Patricia Brown         patricia.brown416@gmail.com
126   S10116        Sarah Rodriguez        sarah.rodriguez909@gmail.com
127   S10117         Charles Garcia         charles.garcia114@gmail.com
128   S10118        Daniel Gonzalez        daniel.gonzalez375@gmail.com
129   S10119           David Wilson           david.wilson354@gmail.com
130    S1012          Robert Miller          robert.miller151@gmail.com
131   S10120         Barbara Miller         barbara.miller548@gmail.com
132   S10121          Matthew Davis          matthew.davis822@gmail.com
133   S10122          Joseph Wilson          joseph.wilson423@gmail.com
134   S10123          Mary Anderson           mary.anderson92@gmail.com
135   S10124          Sarah Johnson          sarah.johnson166@gmail.com
136   S10125          Linda Johnson          linda.johnson594@gmail.com
137   S10126            Susan Davis            susan.davis950@gmail.com
138   S10127             Lisa Smith             lisa.smith925@gmail.com
139   S10128    Elizabeth Rodriguez    elizabeth.rodriguez831@gmail.com
140   S10129          Robert Miller          robert.miller644@gmail.com
141    S1013        Sandra Gonzalez         sandra.gonzalez76@gmail.com
142   S10130        Nancy Hernandez        nancy.hernandez781@gmail.com
143   S10131          Joseph Garcia          joseph.garcia105@gmail.com
144   S10132          Sandra Garcia          sandra.garcia710@gmail.com
145   S10133             Lisa Smith             lisa.smith565@gmail.com
146   S10134            Lisa Garcia            lisa.garcia744@gmail.com
147   S10135        Sandra Anderson        sandra.anderson241@gmail.com
148   S10136          Daniel Thomas          daniel.thomas830@gmail.com
149   S10137        Margaret Martin        margaret.martin717@gmail.com
150   S10138           James Garcia           james.garcia574@gmail.com
151   S10139        Patricia Taylor        patricia.taylor813@gmail.com
152    S1014        Daniel Martinez        daniel.martinez765@gmail.com
153   S10140        Linda Rodriguez        linda.rodriguez675@gmail.com
154   S10141          Robert Taylor          robert.taylor647@gmail.com
155   S10142           Karen Thomas           karen.thomas956@gmail.com
156   S10143            Mark Thomas            mark.thomas490@gmail.com
157   S10144          Michael Brown          michael.brown987@gmail.com
158   S10145         William Miller         william.miller422@gmail.com
159   S10146         Jessica Taylor         jessica.taylor267@gmail.com
160   S10147      Charles Rodriguez      charles.rodriguez542@gmail.com
161   S10148         William Martin         william.martin725@gmail.com
162   S10149       Richard Williams       richard.williams582@gmail.com
163   S10150      Margaret Anderson      margaret.anderson257@gmail.com
164   S10151          William Brown          william.brown623@gmail.com
165   S10152      Michael Rodriguez      michael.rodriguez287@gmail.com
166   S10153        Robert Anderson         robert.anderson58@gmail.com
167   S10154          Jessica Smith          jessica.smith202@gmail.com
168   S10155         Jennifer Moore         jennifer.moore394@gmail.com
169   S10156          Sandra Martin          sandra.martin364@gmail.com
170   S10157      Charles Hernandez      charles.hernandez329@gmail.com
171   S10158           Betty Thomas           betty.thomas834@gmail.com
172   S10159         Jennifer Moore         jennifer.moore690@gmail.com
173   S10160           James Miller            james.miller43@gmail.com
174   S10161       Michael Gonzalez       michael.gonzalez243@gmail.com
175   S10162           James Thomas           james.thomas969@gmail.com
176   S10163          James Johnson           james.johnson89@gmail.com
177   S10164         Jessica Thomas         jessica.thomas678@gmail.com
178   S10165             Mary Lopez             mary.lopez453@gmail.com
179   S10166      Jennifer Gonzalez      jennifer.gonzalez824@gmail.com
180   S10167          Thomas Thomas          thomas.thomas894@gmail.com
181   S10168          Sandra Martin          sandra.martin735@gmail.com
182   S10169          Charles Smith          charles.smith112@gmail.com
183   S10170            Linda Jones            linda.jones459@gmail.com
184   S10171       Robert Hernandez       robert.hernandez613@gmail.com
185   S10172             Mary Brown             mary.brown500@gmail.com
186   S10173            Linda Davis            linda.davis229@gmail.com
187   S10174         Jessica Martin         jessica.martin453@gmail.com
188   S10175          Sandra Martin           sandra.martin56@gmail.com
189   S10176            Mary Garcia            mary.garcia320@gmail.com
190   S10177            Sarah Lopez            sarah.lopez679@gmail.com
191   S10178          Matthew Moore          matthew.moore277@gmail.com
192   S10179        Margaret Martin         margaret.martin13@gmail.com
193   S10180           John Johnson           john.johnson284@gmail.com
194   S10181         Richard Miller         richard.miller807@gmail.com
195   S10182             Lisa Smith             lisa.smith305@gmail.com
196   S10183       Anthony Martinez       anthony.martinez126@gmail.com
197   S10184        Jennifer Miller        jennifer.miller325@gmail.com
198   S10185          Richard Lopez          richard.lopez705@gmail.com
199   S10186          Michael Smith          michael.smith690@gmail.com
200   S10187         Betty Williams         betty.williams198@gmail.com
201   S10188          John Martinez           john.martinez32@gmail.com
202   S10189        Anthony Johnson        anthony.johnson450@gmail.com
203   S10190          Anthony Lopez          anthony.lopez836@gmail.com
204   S10191         Sarah Gonzalez         sarah.gonzalez691@gmail.com
205   S10192             Lisa Brown             lisa.brown173@gmail.com
206   S10193        Jennifer Wilson        jennifer.wilson164@gmail.com
207   S10194      Patricia Williams      patricia.williams238@gmail.com
208   S10195   Christopher Anderson   christopher.anderson817@gmail.com
209   S10196             John Smith             john.smith317@gmail.com
210   S10197         Sarah Anderson         sarah.anderson189@gmail.com
211   S10198           Susan Taylor           susan.taylor720@gmail.com
212   S10199            Lisa Garcia            lisa.garcia896@gmail.com
213   S10200          Richard Moore          richard.moore430@gmail.com
214   S10201         Patricia Jones         patricia.jones347@gmail.com
215   S10202      Elizabeth Johnson      elizabeth.johnson787@gmail.com
216   S10203             Lisa Moore             lisa.moore855@gmail.com
217   S10204          Matthew Smith          matthew.smith338@gmail.com
218   S10205   Christopher Gonzalez    christopher.gonzalez79@gmail.com
219   S10206             Mark Davis             mark.davis837@gmail.com
220   S10207         Patricia Davis         patricia.davis481@gmail.com
221   S10208        Robert Martinez        robert.martinez466@gmail.com
222   S10209          Linda Johnson          linda.johnson149@gmail.com
223   S10210          Thomas Taylor          thomas.taylor684@gmail.com
224   S10211          Richard Brown          richard.brown291@gmail.com
225   S10212      Margaret Gonzalez      margaret.gonzalez127@gmail.com
226   S10213            Nancy Smith            nancy.smith551@gmail.com
227   S10214      Jessica Hernandez      jessica.hernandez594@gmail.com
228   S10215      Patricia Martinez      patricia.martinez386@gmail.com
229   S10216           Thomas Moore           thomas.moore568@gmail.com
230   S10217            Nancy Davis            nancy.davis695@gmail.com
231   S10218             Mark Davis             mark.davis188@gmail.com
232   S10219        Joseph Gonzalez        joseph.gonzalez205@gmail.com
233   S10220       Margaret Jackson       margaret.jackson329@gmail.com
234   S10221      Matthew Rodriguez      matthew.rodriguez124@gmail.com
235   S10222         James Martinez         james.martinez674@gmail.com
236   S10223         Susan Anderson         susan.anderson360@gmail.com
237   S10224             John Davis             john.davis673@gmail.com
238   S10225           Linda Taylor           linda.taylor708@gmail.com
239   S10226         Robert Jackson         robert.jackson198@gmail.com
240   S10227          Daniel Thomas          daniel.thomas308@gmail.com
241   S10228         William Miller         william.miller901@gmail.com
242   S10229            Nancy Davis            nancy.davis860@gmail.com
243   S10230          Charles Davis          charles.davis910@gmail.com
244   S10231         Richard Miller         richard.miller423@gmail.com
245   S10232         Matthew Martin         matthew.martin681@gmail.com
246   S10233            Karen Lopez            karen.lopez395@gmail.com
247   S10234         Margaret Moore          margaret.moore23@gmail.com
248   S10235      Jennifer Gonzalez      jennifer.gonzalez551@gmail.com
249   S10236          John Williams          john.williams270@gmail.com
250   S10237          Barbara Smith          barbara.smith781@gmail.com
251   S10238      Richard Hernandez      richard.hernandez711@gmail.com
252   S10239         Jennifer Smith         jennifer.smith356@gmail.com
253   S10240        Thomas Martinez        thomas.martinez607@gmail.com
254   S10241          Daniel Martin          daniel.martin809@gmail.com
255   S10242           Sarah Taylor           sarah.taylor389@gmail.com
256   S10243           John Jackson           john.jackson572@gmail.com
257   S10244       Michael Anderson       michael.anderson276@gmail.com
258   S10245           Sandra Jones           sandra.jones513@gmail.com
259   S10246         David Martinez         david.martinez989@gmail.com
260   S10247          Karen Johnson          karen.johnson461@gmail.com
261   S10248            Betty Smith            betty.smith234@gmail.com
262   S10249           David Taylor           david.taylor421@gmail.com
263   S10250         Daniel Jackson         daniel.jackson122@gmail.com
264   S10251       Matthew Gonzalez        matthew.gonzalez34@gmail.com
265   S10252             John Brown             john.brown387@gmail.com
266   S10253          Richard Smith          richard.smith915@gmail.com
267   S10254            Linda Moore            linda.moore708@gmail.com
268   S10255           Linda Garcia           linda.garcia392@gmail.com
269   S10256            David Jones            david.jones466@gmail.com
270   S10257       Matthew Williams        matthew.williams24@gmail.com
271   S10258        Jennifer Wilson        jennifer.wilson827@gmail.com
272   S10259           Mary Johnson           mary.johnson371@gmail.com
273   S10260          Susan Johnson          susan.johnson445@gmail.com
274   S10261  Christopher Rodriguez  christopher.rodriguez847@gmail.com
275   S10262          William Lopez          william.lopez896@gmail.com

### 2. Get the count before cleaning (to verify it worked)

In [9]:
initial_count = len(customer_df)
initial_count

1864

### 3. Check duplicates

In [10]:
customer_df.duplicated().sum()

np.int64(0)

*Data is already cleaned, we do not need to clean it. You can check
rest of the tables that duplicate values are present there or not.*

### Task 1: Total revenue( in millions)

In [108]:
vehicleSold_df = dfs['vehicle_sold']
total = round(vehicleSold_df['sale_price'].sum()/1000000,2)
total_revenue = f"Total revenue: {total}M"
total_revenue

'Total revenue: 95.53M'

### Task 2: Model with highest sales volume

In [109]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
merge_df = pd.merge(vehicleSold_df, vehicleInfo_df, on = 'vehicle_id', how = 'inner')
highest_sales = merge_df.groupby('model')['sale_price'].sum().reset_index()
sales_by_model = highest_sales.rename(columns = {'sale_price': 'highest_sales_revenue'})
top_model = sales_by_model.sort_values(by = 'highest_sales_revenue', ascending = False).head(1)
top_model

    model  highest_sales_revenue
165  Semi                2016000

### Task 3: Average sale price of a vehicle

In [17]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
merge_df = pd.merge(vehicleSold_df, vehicleInfo_df, on = 'vehicle_id', how = 'inner')
average_price = merge_df.groupby('make')['sale_price'].mean().reset_index()
rename_column = average_price.rename(columns = {'sale_price': 'average_sale_price'})
avg_sales = rename_column.sort_values(by = 'average_sale_price', ascending = False)
avg_sales

        make  average_sale_price
3      Tesla        57875.000000
5    Unknown        52650.796569
1       Ford        46218.750000
4     Toyota        39007.692308
2      Honda        29636.000000
0  Chevrolet        22850.000000
6        kia        17600.000000

### Task 4: Vehicle sales count in 'NORTH' region

In [18]:
inventory_df = dfs['inventory_details']
vehicleSold_df = dfs['vehicle_sold']
merge_df = pd.merge(inventory_df, vehicleSold_df, on = 'sale_id', how = 'inner')
north_region = merge_df[merge_df['region'] == 'North']
north_count = north_region.shape[0]
print(f"Count of vehicle sold in North: {north_count}")

Count of vehicle sold in North: 486

### Task 5: What is the most common body_type in the inventory?

In [19]:
vehicleInfo_df = dfs['vehicle_info']
common_type = vehicleInfo_df['body_type'].value_counts().nlargest(1).reset_index()
rename_col = common_type.rename(columns= {'body_type': 'most_common_body'})
rename_col

  most_common_body  count
0              SUV    595

### Task 6: Which region has the highest average days_on_lot?

In [20]:
vehicleSold_df = dfs['vehicle_sold']
inventory_df = dfs['inventory_details']
merge_df = pd.merge(vehicleSold_df, inventory_df, on = 'sale_id', how = 'inner')
merge_df['days_on_lot'] = pd.to_numeric(merge_df['days_on_lot'])
highest_avg = round(merge_df.groupby('region')['days_on_lot'].mean(),2).nlargest(1).reset_index()
rename_col = highest_avg.rename(columns= {'days_on_lot': 'highest_avg_days_on_lot'})
result = rename_col.sort_values(by= 'highest_avg_days_on_lot', ascending = False)
result

  region  highest_avg_days_on_lot
0   East                    76.94

### Task 7: What is the average mileage of vehicles sold in the 'WEST' region?

In [21]:
inventory_df = dfs['inventory_details']
west_region = inventory_df[inventory_df['region'] == 'West']
avg_mileage = round(west_region['mileage'].mean(),2)
print(f"Average mileage of vehicles sold in the 'WEST' region: {avg_mileage}")

Average mileage of vehicles sold in the 'WEST' region: 16034.33

### Task 8: Identify the top 10 customers by total purchase value.

In [22]:
customers_df = dfs['customers']
vehicleSold_df = dfs['vehicle_sold']
merge_df = pd.merge(customers_df, vehicleSold_df, on = 'sale_id', how = 'inner')
total_purchase = merge_df.groupby('customer_name')['sale_price'].sum().nlargest(10).reset_index()
rename_col = total_purchase.rename(columns = {'sale_price': 'total_purchase'})
total_purchase = rename_col.sort_values(by= 'total_purchase', ascending = False)
total_purchase

       customer_name  total_purchase
0  Michael Rodriguez          843000
1      Robert Miller          535000
2  Jessica Hernandez          498000
3        Lisa Garcia          491500
4    Barbara Johnson          454500
5       Betty Garcia          431000
6      Barbara Moore          427000
7      Michael Brown          426000
8       James Wilson          408000
9      Linda Johnson          401500

### Task 9: What is the average discount/premium (Difference between MSRP and Sale Price) for Electric vehicles?

In [23]:
vehicleInfo_df = dfs['vehicle_info']
vehicleSold_df = dfs['vehicle_sold']
merge_df = pd.merge(vehicleInfo_df, vehicleSold_df, on= 'vehicle_id', how = 'inner')
elec_vehicle = merge_df[merge_df['fuel_type'] == 'Electric']
elec_vehicle['difference'] = elec_vehicle['sale_price'] - elec_vehicle['msrp']
elec_vehicle = round(elec_vehicle['difference'].mean(),2)
print(f"Average difference b/w msrp and sale price for electric vehicles is: {elec_vehicle}")

Average difference b/w msrp and sale price for electric vehicles is: 2516.95

### Task 10: Which model year (e.g., 2024 models) is currently selling the fastest (lowest avg days on lot)?

In [24]:
vehicleInfo_df = dfs['vehicle_info']
vehicleSold_df = dfs['vehicle_sold']

# 1. Merge the dataframes
merge_df = pd.merge(vehicleInfo_df, vehicleSold_df, on='vehicle_id', how='inner')

# 2. CONVERT 'days_on_lot' to numeric (This fixes the TypeError)
# errors='coerce' will turn any non-numeric junk into NaN so it doesn't break the math
merge_df['days_on_lot'] = pd.to_numeric(merge_df['days_on_lot'], errors='coerce')

# 3. Calculate the AVERAGE days_on_lot for each year
avg_days_per_year = merge_df.groupby('year')['days_on_lot'].mean().nsmallest(1).reset_index()

rename_col = avg_days_per_year.rename(columns = {'days_on_lot': 'avg_days_on_lot'})

# 4. Sort by days_on_lot (Lowest/fastest at the top)
most_selling_year = rename_col.sort_values(by='avg_days_on_lot', ascending=True)

# 5. Display the result
most_selling_year

   year  avg_days_on_lot
0  2025              1.0

### Task 11: List all vehicle models that sold for more than their MSRP

In [25]:
vehicleInfo_df = dfs['vehicle_info']
vehicleSold_df = dfs['vehicle_sold']
pd.set_option('display.max_rows', None)
# 1. Merge the dataframes
merge_df = pd.merge(vehicleInfo_df, vehicleSold_df, on='vehicle_id', how='inner')
listing_vehicle = merge_df[merge_df['sale_price'] > merge_df['msrp']]
vehicle_sold_more_than_their_msrp = listing_vehicle[['model','msrp', 'sale_price']]
vehicle_sold_more_than_their_msrp.sort_values(by = 'sale_price', ascending = True)

                    model    msrp  sale_price
1120             Maverick   25000       29000
494              Maverick   25000       29000
495              Maverick   25000       29000
847              Maverick   26000       30000
1012                Camry   30000       30500
468                   BRZ   30000       31000
469                   BRZ   30000       31000
844              Maverick   26000       31000
845              Maverick   26000       31000
846              Maverick   26000       31000
1715             Maverick   27000       32000
629                  GR86   30000       32000
804                  GR86   31000       33000
802                  GR86   31000       33000
803                  GR86   31000       33000
1114                 GR86   32000       34000
1726                 GR86   32000       35000
1193                 GR86   33000       35000
1029               Tacoma   38000       39500
910                Sienna   40000       42000
1714               Sienna   40000       42000
911                Sienna   40000       42000
963                Camaro   40000       42000
912                Sienna   40000       42000
1201               Tacoma   41000       42000
493               4Runner   42000       43000
1599               Sienna   41000       43000
492               4Runner   42000       43000
1097               Sienna   42000       44000
435                     Z   42000       45000
434                     Z   42000       45000
432                     Z   42000       45000
431                     Z   42000       45000
430                     Z   42000       45000
433                     Z   42000       45000
1627               Bronco   42000       45000
1151                    Z   43000       46000
877               4Runner   45000       47000
876               4Runner   45000       47000
875               4Runner   45000       47000
1152                    Z   43000       47000
914               Mustang   45000       48000
913               Mustang   45000       48000
915               Mustang   45000       48000
1736                    Z   45000       48000
916               Mustang   45000       48000
1588               Bronco   45000       48000
618                 Crown   48000       49000
609          Civic Type R   45000       50000
843                 Crown   50000       51000
842                 Crown   50000       51000
610          Civic Type R   45000       51000
841                 Crown   50000       51000
840                 Crown   50000       51000
401                Bronco   48000       52000
795             Telluride   50000       52000
796             Telluride   50000       52000
797             Telluride   50000       52000
808          Civic Type R   46000       52000
400                Bronco   48000       52000
810          Civic Type R   46000       52000
811          Civic Type R   46000       52000
809          Civic Type R   46000       52000
398                Bronco   48000       52000
399                Bronco   48000       52000
403                Bronco   48000       52000
402                Bronco   48000       52000
812          Civic Type R   46000       55000
878                Bronco   50000       55000
879                Bronco   50000       55000
880                Bronco   50000       55000
978                 Titan   52000       58000
984               Model 3   41000       58000
960                   CLA   42000       58000
953                Accord   35000       58000
990             Silverado   49000       58000
1452           Pathfinder   42000       58000
1246                Titan   56000       58000
1500               Accord   40000       58000
1472                Ariya   54000       58000
1484         Civic Type R   50000       58000
1490                 Leaf   33000       58000
1495                  GLC   55000       58000
997                  RAV4   35000       58000
1506               Sentra   28000       58000
790                 Ariya   48000       58000
1466            Ridgeline   44000       58000
998              Explorer   39000       58000
1030                   X3   47000       58000
1445                 CR-V   41000       58000
1100              Odyssey   39000       58000
1106             Renegade   25000       58000
1112                Ariya   49000       58000
1307                 CR-V   39000       58000
1300                  CLA   45000       58000
1124                CX-90   52000       58000
1134               Sonata   32000       58000
1140                   Q4   55000       58000
1146                  EQB   54000       58000
1158                   Q5   46000       58000
1167                  GLB   41000       58000
1295                Rogue   34000       58000
1195                Civic   26000       58000
1199                Titan   55000       58000
1286                 CR-V   38000       58000
1207                  CLA   44000       58000
1212               Accord   36000       58000
1222                 RAV4   36000       58000
1238                Pilot   46000       58000
1315           Pathfinder   40000       58000
1330            Ridgeline   42000       58000
1338                Ariya   52000       58000
1353         Civic Type R   48000       58000
1019                  GLC   51000       58000
1439                  CLA   47000       58000
1262              Odyssey   41000       58000
1434                Rogue   36000       58000
1412              Odyssey   43000       58000
1392                Pilot   48000       58000
1382                 CR-V   40000       58000
1044            Silverado   45000       58000
1048                 RAV4   34000       58000
1010              Elantra   23500       58000
1378               Sentra   26000       58000
1053                 CX-5   30000       58000
1061                Rogue   29000       58000
1065                  GLC   52000       58000
1075                Pilot   41000       58000
1085             Colorado   34000       58000
1094               Blazer   37000       58000
1365                  GLC   53000       58000
1359                 Leaf   31000       58000
789                 Ariya   48000       58000
1371               Accord   38000       58000
788                 Ariya   48000       58000
9                 Model 3   42000       58000
674                  Kona   36000       58000
177                  CX-5   29000       58000
176                  CX-5   29000       58000
175                  CX-5   29000       58000
174                  CX-5   29000       58000
161                  CR-V   34000       58000
153                Sienna   37000       58000
440                Blazer   35000       58000
265        Grand Cherokee   45000       58000
152                Sienna   37000       58000
107            Highlander   42000       58000
439                Blazer   35000       58000
438                Blazer   35000       58000
632   Model Y Performance   55000       58000
106            Highlander   42000       58000
641                 MX-30   34000       58000
642                 MX-30   34000       58000
151                Sienna   37000       58000
643                 MX-30   34000       58000
266        Grand Cherokee   45000       58000
268        Grand Cherokee   45000       58000
471                 CX-90   48000       58000
393                 Supra   56000       58000
500                 Camry   30000       58000
501                 Camry   30000       58000
506              Traverse   38000       58000
507              Traverse   38000       58000
539               C-Class   48000       58000
267        Grand Cherokee   45000       58000
540               C-Class   48000       58000
392                 Supra   56000       58000
389                    A5   46000       58000
388                    A5   46000       58000
359                  Kona   35000       58000
358                  Kona   35000       58000
357                  Kona   35000       58000
356                  Kona   35000       58000
541               C-Class   48000       58000
470                 CX-90   48000       58000
441                Blazer   35000       58000
676                  Kona   36000       58000
718                    A5   47000       58000
719                    A5   47000       58000
732              Traverse   39000       58000
733              Traverse   39000       58000
395                 Supra   56000       58000
396                 Supra   56000       58000
397                 Supra   56000       58000
404                Bronco   48000       58000
734              Traverse   39000       58000
766               Odyssey   40000       58000
40                   RAV4   32000       58000
26              Silverado   48000       58000
25              Silverado   48000       58000
24              Silverado   48000       58000
12                Model 3   42000       58000
11                Model 3   42000       58000
10                Model 3   42000       58000
717                    A5   47000       58000
675                  Kona   36000       58000
41                   RAV4   32000       58000
50                  F-150   48000       58000
694              Cherokee   34000       58000
695              Cherokee   34000       58000
696              Cherokee   34000       58000
105            Highlander   42000       58000
76                   CR-V   34000       58000
42                   RAV4   32000       58000
436                Blazer   35000       58000
437                Blazer   35000       58000
74                   CR-V   34000       58000
73                   CR-V   34000       58000
60                Model Y   53000       58000
54                  F-150   48000       58000
53                  F-150   48000       58000
52                  F-150   48000       58000
51                  F-150   48000       58000
394                 Supra   56000       58000
1129                Supra   57000       60000
1037            Silverado   58000       60000
1079            Silverado   59000       61000
1007                Tahoe   62000       64000
630            Dark Horse   60000       65000
94                 Tucson   31000       65000
1737         Land Cruiser   60000       65000
631                    M2   65000       68000
619             Lightning   65000       68000
628               Z Nismo   65000       70000
836               Z Nismo   67000       75000
835               Z Nismo   67000       75000
834               Z Nismo   67000       75000
807             Lightning   70000       75000
806             Lightning   70000       75000
805             Lightning   70000       75000
1119              Z Nismo   68000       75000
1115            Lightning   72000       76000
1740                   GX   68000       78000
611          Silverado EV   75000       80000
794              Corvette   75000       82000
793              Corvette   75000       82000
792              Corvette   75000       82000
1118             Corvette   78000       85000
839          Silverado EV   80000       90000
838          Silverado EV   80000       90000
837          Silverado EV   80000       90000
1578           Cybertruck   80000       95000
412            Cybertruck   80000       95000
415            Cybertruck   80000       95000
414            Cybertruck   80000       95000
413            Cybertruck   80000       95000
1734             Corvette   80000       95000
411            Cybertruck   80000       95000
417            Cybertruck   80000       95000
416            Cybertruck   80000       95000
780                    GT   95000       98000
781                    GT   95000       98000
782                    GT   95000       98000
817            Cybertruck   85000      105000
1125               LX 600   95000      105000
1730                   LX   95000      105000
59                Model Y   53000      105000
62                Model Y   53000      105000
64                Model Y   53000      105000
816            Cybertruck   85000      110000
815            Cybertruck   85000      110000
814            Cybertruck   85000      110000
813            Cybertruck   85000      110000
818            Cybertruck   85000      110000
634        Corvette E-Ray  105000      120000
962                  GT-R  115000      125000
605                  GT-R  120000      125000
1116                  RS6  120000      125000
777                   RS6  125000      130000
776                   RS6  125000      130000
778                   RS6  125000      130000
1150                  RS7  130000      135000
603               G-Wagon  150000      160000
622                  Semi  150000      160000
620                    XM  160000      165000
602                    R8  160000      170000
820                    XM  165000      175000
621                    XM  160000      175000
821                    XM  165000      175000
822                    XM  165000      175000
819                    XM  165000      175000
935               G-Wagon  160000      180000
920                  Semi  160000      180000
921                  Semi  160000      180000
922                  Semi  160000      180000
923                  Semi  160000      180000
933               G-Wagon  160000      180000
934               G-Wagon  160000      180000
594              Roadster  200000      210000
595              Roadster  200000      250000
596              Roadster  200000      250000
597              Roadster  200000      250000
599                    GT  500000      550000

### Task 12: Find the total revenue contributed by each fuel_type.

In [26]:
vehicleInfo_df = dfs['vehicle_info']
vehicleSold_df = dfs['vehicle_sold']
pd.set_option('display.max_rows', None)
# 1. Merge the dataframes
merge_df = pd.merge(vehicleInfo_df, vehicleSold_df, on='vehicle_id', how='inner')
total_revenue = merge_df.groupby('fuel_type')['sale_price'].sum().reset_index()
total_revenue_by_each_fuel_type = total_revenue.rename(columns = {'sale_price': 'total_revenue'})
total_revenue_by_each_fuel_type.sort_values(by = 'total_revenue', ascending = False)

  fuel_type  total_revenue
2  Gasoline       54892100
1  Electric       24956000
3    Hybrid       11692100
0    Diesel        3471500
4  Hydrogen         436000
5      PHEV          87000

### Task 13: Calculate the cumulative revenue generated as sale_id increases.

In [27]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
merge_df = pd.merge(vehicleSold_df, vehicleInfo_df, on= 'vehicle_id' , how='inner')
merge_df['cumulative_revenue'] = merge_df['sale_price'].cumsum()
cumulative_rev = merge_df[['sale_id','model','sale_price','cumulative_revenue']]
cumulative_rev

     sale_id                model  sale_price  cumulative_revenue
0      S1001              Corolla       23200               23200
1      S1002                F-150       43500               66700
2      S1003                Civic       21000               87700
3      S1004              Model 3       58000              145700
4      S1005                   X5       58000              203700
5      S1006               Accord       27500              231200
6      S1007               Altima       19500              250700
7      S1008            Silverado       58000              308700
8      S1009                   A4       36000              344700
9      S1010              Elantra       22500              367200
10     S1011              Mustang       39000              406200
11     S1012              C-Class       42000              448200
12     S1013                 RAV4       58000              506200
13     S1014             Explorer       33000              539200
14     S1501                Camry       25800              565000
15     S1502                F-150       58000              623000
16     S1503               Accord       28100              651100
17     S1504              Model Y       53000              704100
18     S1505                   X3       43500              747600
19     S1506                 CR-V       58000              805600
20     S1507                Rogue       25000              830600
21     S1508                Tahoe       55000              885600
22     S1509                   Q5       41000              926600
23     S1510               Tucson       30500              957100
24     S1511                Civic       24500              981600
25     S1512                  GLC       46500             1028100
26     S1513           Highlander       58000             1086100
27     S1514                 Edge       30000             1116100
28     S1515              Model 3       40000             1156100
29     S1516             5 Series       51000             1207100
30     S1517                Pilot       38000             1245100
31     S1518               Sentra       18000             1263100
32     S1519              Equinox       27000             1290100
33     S1520                   A6       52000             1342100
34     S1521             Santa Fe       35500             1377600
35     S1522             Explorer       37500             1415100
36     S1523              E-Class       54000             1469100
37     S1524               Sienna       58000             1527100
38     S1525              Mustang       28500             1555600
39     S1531                 CR-V       32500             1588100
40     S1537                  GLC       46500             1634600
41     S1544              Equinox       27000             1661600
42     S2554              Model Y       53000             1714600
43     S2556                 CR-V       58000             1772600
44     S2557                Rogue       25000             1797600
45     S2560               Tucson       65000             1862600
46     S3052                F-150       47000             1909600
47     S3057                Rogue       25000             1934600
48     S3058                Tahoe       55000             1989600
49     S3551                Camry       25800             2015400
50     S3552                F-150       47000             2062400
51     S3554              Model Y      105000             2167400
52     S4254              Model Y       58000             2225400
53     S5002                F-150       47000             2272400
54     S6001             Sportage       31500             2303900
55     S6002              Outback       33800             2337700
56     S6003                 CX-5       58000             2395700
57     S6004             Wrangler       54500             2450200
58     S6005               Tucson       30200             2480400
59     S6006               RX 350       49000             2529400
60     S6007               Tiguan       26500             2555900
61     S6008           Highlander       43000             2598900
62     S6009              Mustang       41000             2639900
63     S6010              Model 3       39000             2678900
64     S6011             3 Series       42500             2721400
65     S6012                Civic       18500             2739900
66     S6013                F-150       50000             2789900
67     S6014              Equinox       27000             2816900
68     S6015                   Q7       58000             2874900
69     S6016                  GLE       58000             2932900
70     S6017               Sonata       27200             2960100
71     S6018                Rogue       32500             2992600
72     S6019             Explorer       35000             3027600
73     S6020               Tacoma       34500             3062100
74     S6021            Telluride       47500             3109600
75     S6022             Forester       28000             3137600
76     S6023                    3       23000             3160600
77     S6024       Grand Cherokee       58000             3218600
78     S6025              Model Y       52000             3270600
79     S6026               ES 350       38000             3308600
80     S6027                Jetta       22500             3331100
81     S6028                 CR-V       33000             3364100
82     S6029            Silverado       53000             3417100
83     S6030                   A3       33500             3450600
84     S6031              A-Class       31000             3481600
85     S6032              Ioniq 5       48000             3529600
86     S6033                Prius       28500             3558100
87     S6034                F-250       58000             3616100
88     S6035           Pathfinder       33000             3649100
89     S6036                   X1       38000             3687100
90     S6037              Model S       85000             3772100
91     S6038                Camry       25000             3797100
92     S6039               Seltos       24000             3821100
93     S6040            Crosstrek       30500             3851600
94     S6041              Odyssey       36500             3888100
95     S6042               Malibu       21000             3909100
96     S6043                   Q3       36000             3945100
97     S6044                  CLA       37000             3982100
98     S6045                 Kona       58000             4040100
99     S6046               Sentra       21500             4061600
100    S6047               Ranger       31500             4093100
101    S6048             Colorado       28000             4121100
102    S6049             4 Series       48000             4169100
103    S6050              Model X       95000             4264100
104    S6051              Corolla       22000             4286100
105    S6052                F-150       58000             4344100
106    S6053                Pilot       38000             4382100
107    S6054                   A5       58000             4440100
108    S6055                  GLA       37000             4477100
109    S7001                Supra       58000             4535100
110    S7002               Bronco       52000             4587100
111    S7003               Accord       31000             4618100
112    S7004           Cybertruck       95000             4713100
113    S7005                   M3       74000             4787100
114    S7006            Ridgeline       35000             4822100
115    S7007                    Z       45000             4867100
116    S7008               Blazer       58000             4925100
117    S7009               e-tron       70000             4995100
118    S7010             Palisade       44500             5039600
119    S7011       Mustang Mach-E       53000             5092600
120    S7012              S-Class      105000             5197600
121    S7013                Venza       31500             5229100
122    S7014           Expedition       62000             5291100
123    S7015                  EV6       50000             5341100
124    S7016                  BRZ       31000             5372100
125    S7017                CX-90       58000             5430100
126    S7018            Gladiator       41000             5471100
127    S7019               GX 460       55000             5526100
128    S7020                 ID.4       42000             5568100
129    S7021             Passport       38000             5606100
130    S7022               Camaro       32000             5638100
131    S7023                  RS5       78000             5716100
132    S7024                  GLB       39500             5755600
133    S7025              Ioniq 6       45000             5800600
134    S7026                 Leaf       24000             5824600
135    S7027              4Runner       43000             5867600
136    S7028             Maverick       29000             5896600
137    S7029                   X7       79000             5975600
138    S7030              Model 3       38000             6013600
139    S7031                Camry       58000             6071600
140    S7032                F-150       55000             6126600
141    S7033                Civic       23000             6149600
142    S7034             Traverse       58000             6207600
143    S7035                   A8       82000             6289600
144    S7036                  GLS       83000             6372600
145    S7037               Venice       20500             6393100
146    S7038               Armada       48000             6441100
147    S7039               Avalon       36000             6477100
148    S7040                F-350       71000             6548100
149    S7041                   i4       58000             6606100
150    S7042              Model Y       52000             6658100
151    S7043                 HR-V       25500             6683600
152    S7044             Suburban       60000             6743600
153    S7045                   Q8       72000             6815600
154    S7046              C-Class       58000             6873600
155    S7047           Santa Cruz       26000             6899600
156    S7048             Frontier       33000             6932600
157    S7049        Corolla Cross       27500             6960100
158    S7050             EcoSport       19000             6979100
159    S7051               Tacoma       33000             7012100
160    S7052             Explorer       37000             7049100
161    S7053             8 Series       89000             7138100
162    S7054              Model S       88000             7226100
163    S7055              Insight       25000             7251100
164    S8001              Corolla       23200             7274300
165    S8002                F-150       43500             7317800
166    S8003                Civic       21000             7338800
167    S8004              Model 3       58000             7396800
168    S8005                   X5       58000             7454800
169    S8006               Accord       27500             7482300
170    S8007               Altima       19500             7501800
171    S8008            Silverado       58000             7559800
172    S8009                   A4       36000             7595800
173    S8010              Elantra       22500             7618300
174    S8011              Mustang       39000             7657300
175    S8012              C-Class       42000             7699300
176    S8013                 RAV4       58000             7757300
177    S8014             Explorer       33000             7790300
178    S8015                Camry       25800             7816100
179    S8016                F-150       58000             7874100
180    S8017               Accord       28100             7902200
181    S8018              Model Y       53000             7955200
182    S8019                   X3       43500             7998700
183    S8020                 CR-V       58000             8056700
184    S8021                Rogue       25000             8081700
185    S8022                Tahoe       55000             8136700
186    S8023                   Q5       41000             8177700
187    S8024               Tucson       30500             8208200
188    S8025                Civic       24500             8232700
189    S8026                  GLC       46500             8279200
190    S8027           Highlander       58000             8337200
191    S8028                 Edge       30000             8367200
192    S8029              Model 3       40000             8407200
193    S8030             5 Series       51000             8458200
194    S8031                Pilot       38000             8496200
195    S8032               Sentra       18000             8514200
196    S8033              Equinox       27000             8541200
197    S8034                   A6       52000             8593200
198    S8035             Santa Fe       35500             8628700
199    S8036             Explorer       37500             8666200
200    S8037              E-Class       54000             8720200
201    S8038               Sienna       58000             8778200
202    S8039              Mustang       28500             8806700
203    S8040              Model Y      105000             8911700
204    S8041                Camry       25800             8937500
205    S8042                F-150       47000             8984500
206    S8043                 CR-V       32500             9017000
207    S8044              Model 3       40000             9057000
208    S8045                   X5       58000             9115000
209    S8046                   Q5       41000             9156000
210    S8047               Tucson       30500             9186500
211    S8048                  GLC       46500             9233000
212    S8049                Rogue       25000             9258000
213    S8050                Tahoe       55000             9313000
214    S8051             Sportage       31500             9344500
215    S8052              Outback       33800             9378300
216    S8053                 CX-5       58000             9436300
217    S8054             Wrangler       54500             9490800
218    S8055               Tucson       30200             9521000
219    S8056               RX 350       49000             9570000
220    S8057               Tiguan       26500             9596500
221    S8058           Highlander       43000             9639500
222    S8059              Mustang       41000             9680500
223    S8060              Model 3       39000             9719500
224    S8061             3 Series       42500             9762000
225    S8062                Civic       18500             9780500
226    S8063                F-150       50000             9830500
227    S8064              Equinox       27000             9857500
228    S8065                   Q7       58000             9915500
229    S8066                  GLE       58000             9973500
230    S8067               Sonata       27200            10000700
231    S8068                Rogue       32500            10033200
232    S8069             Explorer       35000            10068200
233    S8070               Tacoma       34500            10102700
234    S8071            Telluride       47500            10150200
235    S8072             Forester       28000            10178200
236    S8073                    3       23000            10201200
237    S8074       Grand Cherokee       58000            10259200
238    S8075              Model Y       52000            10311200
239    S8076               ES 350       38000            10349200
240    S8077                Jetta       22500            10371700
241    S8078                 CR-V       33000            10404700
242    S8079            Silverado       53000            10457700
243    S8080                   A3       33500            10491200
244    S8081              A-Class       31000            10522200
245    S8082              Ioniq 5       48000            10570200
246    S8083                Prius       28500            10598700
247    S8084                F-250       58000            10656700
248    S8085           Pathfinder       33000            10689700
249    S8086                   X1       38000            10727700
250    S8087              Model S       85000            10812700
251    S8088                Camry       25000            10837700
252    S8089               Seltos       24000            10861700
253    S8090            Crosstrek       30500            10892200
254    S8091              Odyssey       36500            10928700
255    S8092               Malibu       21000            10949700
256    S8093                   Q3       36000            10985700
257    S8094                  CLA       37000            11022700
258    S8095                 Kona       58000            11080700
259    S8096               Sentra       21500            11102200
260    S8097               Ranger       31500            11133700
261    S8098             Colorado       28000            11161700
262    S8099             4 Series       48000            11209700
263    S8100              Model X       95000            11304700
264    S8101                Supra       58000            11362700
265    S8102               Bronco       52000            11414700
266    S8103               Accord       31000            11445700
267    S8104           Cybertruck       95000            11540700
268    S8105                   M3       74000            11614700
269    S8106            Ridgeline       35000            11649700
270    S8107                    Z       45000            11694700
271    S8108               Blazer       58000            11752700
272    S8109               e-tron       70000            11822700
273    S8110             Palisade       44500            11867200
274    S8111       Mustang Mach-E       53000            11920200
275    S8112              S-Class      105000            12025200
276    S8113                Venza       31500            12056700
277    S8114           Expedition       62000            12118700
278    S8115                  EV6       50000            12168700
279    S8116                  BRZ       31000            12199700
280    S8117                CX-90       58000            12257700
281    S8118            Gladiator       41000            12298700
282    S8119               GX 460       55000            12353700
283    S8120                 ID.4       42000            12395700
284    S8121             Passport       38000            12433700
285    S8122               Camaro       32000            12465700
286    S8123                  RS5       78000            12543700
287    S8124                  GLB       39500            12583200
288    S8125              Ioniq 6       45000            12628200
289    S8126                 Leaf       24000            12652200
290    S8127              4Runner       43000            12695200
291    S8128             Maverick       29000            12724200
292    S8129                   X7       79000            12803200
293    S8130              Model 3       38000            12841200
294    S8131                Camry       58000            12899200
295    S8132                F-150       55000            12954200
296    S8133                Civic       23000            12977200
297    S8134             Traverse       58000            13035200
298    S8135                   A8       82000            13117200
299    S8136                  GLS       83000            13200200
300    S8137               Venice       20500            13220700
301    S8138               Armada       48000            13268700

### Task 14: Which combination of model and body_type yields the highest average profit margin?

In [28]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
merge_df = pd.merge(vehicleSold_df, vehicleInfo_df, on= 'vehicle_id' , how='inner')
merge_df['avg_profit_margin'] = ((merge_df['sale_price'] - merge_df['msrp']) / merge_df['msrp']) * 100
avg_profit = round(merge_df.groupby(['model', 'body_type'])['avg_profit_margin'].mean(),2).reset_index()
avg_profit = avg_profit.sort_values(by = 'avg_profit_margin', ascending = False).head(1)
avg_profit

     model body_type  avg_profit_margin
24  Blazer       SUV              44.25

### Task 15: Total Profit

In [29]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
total_sale = vehicleSold_df['sale_price'].sum()
total_cost = vehicleInfo_df['msrp'].sum()
total_profit = total_sale - total_cost
print(f"Total profit is: {total_profit}")

Total profit is: 33676200

### Task 16: Gross Profit Margin.

In [30]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
total_sale = vehicleSold_df['sale_price'].sum()
total_cost = vehicleInfo_df['msrp'].sum()
GPM = ((total_sale - total_cost) / total_sale) * 100
print(f"Gross profit margin: {GPM:.2f}%")

Gross profit margin: 35.25%

### Task 17: Compare average days_on_lot for "High Mileage" (>50k) vs "Low Mileage" (<50k) vehicles.

In [31]:
vehicleSold_df = dfs['vehicle_sold']
inventory_df = dfs['inventory_details']
merge_df = pd.merge(vehicleSold_df, inventory_df, on = 'sale_id', how = 'inner')
merge_df['mileage_category'] = merge_df['mileage'].apply(
    lambda x: 'High Mileage' if x > 5000 else 'Low Mileage')

result = merge_df.groupby('mileage_category')['days_on_lot'].mean().reset_index()
# Add this to change the name
result = result.rename(columns={'days_on_lot': 'avg_days_on_lot'})
result

  mileage_category  avg_days_on_lot
0     High Mileage        77.491690
1      Low Mileage         4.503503

### Task 18: Identify "Stale Inventory": Models that average more than 100 days on the lot.

In [32]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
merge_df = pd.merge(vehicleSold_df, vehicleInfo_df, on = 'vehicle_id', how = 'inner')
avg_days = round(merge_df.groupby('model')['days_on_lot'].mean(),2).reset_index()
avg_day_on_lot = avg_days[avg_days['days_on_lot'] > 100]
rename_col = avg_day_on_lot.rename(columns = {'days_on_lot': 'avg_days_on_lot'})
rename_col

        model  avg_days_on_lot
2        370Z           150.00
6           6           101.00
8     A-Class           102.00
13         A8           140.00
15     Altima           149.50
17     Armada           210.00
21     Avalon           112.50
36     Camaro           134.00
57     ES 350           109.17
60   EcoSport           195.00
70        Fit           121.25
71       Flex           200.00
86     GX 460           180.00
107        LX           102.20
120     Mirai           112.50
126    Murano           152.00
195      Volt           140.00
200        X4           107.00
210        i3           130.00

### Task 19: Rank regions by their "Sales Efficiency" (Revenue divided by average Days on Lot).

In [55]:
vehicleSold_df = dfs['vehicle_sold']
inventory_df = dfs['inventory_details']
pd.options.display.float_format ='{:.2f}'.format
merge_df = pd.merge(vehicleSold_df, inventory_df, on= 'sale_id' , how = 'inner')
region_summary = merge_df.groupby('region').agg(
total_sale = ('sale_price' , 'sum'),
avg_days = ('days_on_lot', 'mean')
).reset_index()
region_summary['sale_efficiency'] = region_summary['total_sale'] / region_summary['avg_days']
ranked_region = region_summary.sort_values(by = 'sale_efficiency', ascending = False)
ranked_region = ranked_region[['region', 'sale_efficiency']]
ranked_region

  region  sale_efficiency
3   West       1416400.41
1  North        832998.70
2  South        723456.00
0   East         26324.19

### Task 20:  What percentage of total sales come from Hybrid/Electric vehicles vs Gasoline?

In [88]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
merge_df = pd.merge(vehicleSold_df, vehicleInfo_df, on= 'vehicle_id' , how = 'inner')
filter_fuel_type = merge_df[merge_df['fuel_type'].isin(['Hybrid', 'Electric', 'Gasoline'])]
fuel_sales = filter_fuel_type.groupby('fuel_type')['sale_price'].sum().reset_index()
total_sales = fuel_sales['sale_price'].sum()
fuel_sales['total_sales_percentage'] = (fuel_sales['sale_price'] / total_sales) *100
fuel_sales

  fuel_type  sale_price  total_sales_percentage
0  Electric    24956000                   27.26
1  Gasoline    54892100                   59.97
2    Hybrid    11692100                   12.77

### Task 21: Identify potential data entry errors where the sale_price is less than 50% of the MSRP.

In [107]:
vehicleSold_df = dfs['vehicle_sold']
vehicleInfo_df = dfs['vehicle_info']
merge_df = pd.merge(vehicleSold_df, vehicleInfo_df, on= 'vehicle_id' , how = 'inner')
msrp = (merge_df['msrp'] * 50) / 100 
less_than_50_percent_of_msrp = merge_df[merge_df['sale_price'] < msrp ]
less_than_50_percent_of_msrp

,sale_id,vehicle_id,sale_price,days_on_lot,make,model,year,body_type,fuel_type,msrp
1174,S10261,V0544,58000,1,Unknown,S-Class,2024,Sedan,Gasoline,118000
1186,S10273,V0556,58000,1,Unknown,GT-R,2024,Coupe,Gasoline,121000
1300,S10387,V0667,58000,1,Unknown,S-Class,2024,Sedan,Gasoline,120000
1312,S10399,V0678,58000,1,Unknown,GT-R,2024,Coupe,Gasoline,123000